### ISSUE TITLE
don't allow editing piedirectory while the option is disabled

### ISSUE THREAD

**Issue by maskersss** [KingContaria/StandardSettings#21]
idk if the opposite was intentional, but i don't see the benefit in it, and
- this would be consistent with other settings
- would help preventing confusion from someone just downloading mods, changing piedirectory without realising it's disabled, and having to figure out why it doesn't reset

**Comment by contariaa** [comment]
It's because Minecrafts TextWidget class doesnt respect the variable standardsettings toggles, I'll look into it
