### ISSUE TITLE
Inconsistent perspective on world join

### ISSUE THREAD

**Issue by AnonymousRand** [KingContaria/StandardSettings#5]
I have perspective set to 0 (first-person) in my standardoptions.txt. However, sometimes I join in third-person front view when I enter a world from the wall instead. I have tested with both true and false for changeOnResize, with running 6 instances instead of 9 in case it was a lag issue, and with using the full standardoptions.txt in each instance instead of copying the file path of the global file, but none of these seemed to solve the problem. Weirdly enough, the issue doesn't seem to exist when I only play a single instance from my wall (e.g. only pressing "r" or "f" on and then resetting one of the instances), but once I start loading into different instances, the issue comes back. I can link a video example if you want to see what it looks like (also for reference, my change perspectives key is caps in case this conflicted with something in the mod).

Smooth lighting off also seems to correspond to "ao:2" in standardoptions.txt instead of "ao:0" as it normally is, and I'm not sure if this is tied to the inconsistent perspectives bug. All the other settings in standardoptions.txt work as intended.

**Comment by contariaa** [comment]
could you try unbinding your perspective hotkey to make sure the macro isnt accidentally pressing it?

smooth lighting i think is bugged because of sodium which should be fixed there

**Comment by AnonymousRand** [comment]
wow that actually seems to have solved the problem, sorry for the dumb post lol
